# Generated by Django 2.0.6 on 2018-06-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaguemgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particiapant1_id', models.IntegerField()),
                ('particiapant2_id', models.IntegerField()),
                ('participant1_score', models.IntegerField()),
                ('participant2_score', models.IntegerField()),
                ('leagueid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaguemgmt.League')),
            ],
        ),
    ]
